= Build 'n Bump Socket Client

== Background

I am the developer of the PC game https://store.steampowered.com/app/375790/Build_n_Bump/[Build 'n Bump], which features a network mode that requires port forwarding if you want to play online and not just over LAN. Obviously, this has been a sore spot for a lot of players trying to get the achievement for playing every game mode at least once.

A few years ago, I saw that GitHub user euank had created a Node.js project called https://github.com/euank/bnb-bot[bnb-bot] that simulated an online user connecting to your game. Needing to learn Java/Kotlin for my new job, I thought I would tackle the same challenge with a different set of tools.

== How to Use

Download the latest JAR file from the https://github.com/clarknielsen/bump-n-socket/releases[releases] tab.

Make sure the _Build 'n Bump_ game is open first and waiting for a guest to connect. The game will also need to use port 8080, as that port number is hardcoded within the app.

After the game is prepped, run the following command in the same directory as the JAR file:

[source,bash]
----
java -jar bump-n-socket.jar
----

== Development

This repo contains the source code if you'd like to further experiment with it. Note that this is a Kotlin project and relies on a non-Maven dependency. You will need to download and build the https://github.com/Gottox/socket.io-java-client[socket.io-java-client] project separately, then add it to the project as an external library.

I've included a very simple test that creates a socket server with the `MockServer` class. This is intended to simulate receiving messages when the game sends a "menu" or "game setup" update. If you can successfully run the test, you should be good to start tinkering!